export const SITE = {
  website: "https://curadanatureza.receitagratis.com/", 
  author: "Anderson Kochanski",
  profile: "https://receitagratis.com/", 
  desc: "Receita Grátis: Mais de 15 mil receitas, dicas de culinária e o especial Curada Natureza para sua saúde.",
  title: "Receita Grátis",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 10, 
  scheduledPostMargin: 15 * 60 * 1000, 
  showArchives: true,
  showBackButton: true, 
  editPost: {
    enabled: false, 
    text: "Sugerir alteração",
    url: "https://github.com/reportertb2015-blip/portal-receitas/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr", 
  lang: "pt-BR", 
  timezone: "America/Sao_Paulo", 
} as const;
